package com.redylab.redylabsirr.Utilidades;

import android.database.Cursor;
import android.os.Build;
import android.util.Log;
import com.redylab.redylabsirr.database.DatabaseManagerUser;
import org.json.JSONException;
import org.json.JSONObject;


public class Utilidades {
    // Indices para las columnas indicadas en la proyección
    public static final int COLUMNA_ID = 0;
    public static final int COLUMNA_ID_REMOTA  = 1;
    public static final int COLUMNA_NOMB_TRAFO  = 2;
    public static final int COLUMNA_CAPACIDAD  = 3;
    public static final int COLUMNA_ZONAUR  = 4;
    public static final int COLUMNA_MPIO  = 5;
    public static final int COLUMNA_PROPIEDAD_TRAFO  = 6;
    public static final int COLUMNA_TIPO  = 7;
    public static final int COLUMNA_LATI_TRAFO  = 8;
    public static final int COLUMNA_LONG_TRAFO  = 9;
    public static final int COLUMNA_ALT_TRAFO  = 10;
    public static final int COLUMNA_TIPO_TRAFO  = 11;
    public static final int COLUMNA_FECH_LEVANT_TRAFO  = 12;
    public static final int COLUMNA_OBSERVACION_TRAFO  = 13;
    public static final int COLUMNA_NRO_POSTES_TRAFO  = 14;
    public static final int COLUMNA_ESPACIO_N1  = 15;
    public static final int COLUMNA_NRO_POSTE_CORRESP  = 16;
    public static final int COLUMNA_NOMB_NODO  = 17;
    public static final int COLUMNA_ID_TRAFO_NODO  = 18;
    public static final int COLUMNA_LATI_NODO  = 19;
    public static final int COLUMNA_LONG_NODO  = 20;
    public static final int COLUMNA_ALTI_NODO  = 21;
    public static final int COLUMNA_ALTURA_NODO  = 22;
    public static final int COLUMNA_MATERIAL_NODO  = 23;
    public static final int COLUMNA_ESTRUCT_1_NODO  = 24;
    public static final int COLUMNA_TIPO_1_ESTRUCT  = 25;
    public static final int COLUMNA_ESTRUCT_2_NODO  = 26;
    public static final int COLUMNA_TIPO_2_ESTRUCT  = 27;
    public static final int COLUMNA_ESTRUCT_3_NODO  = 28;
    public static final int COLUMNA_TIPO_3_ESTRUCT  = 29;
    public static final int COLUMNA_ESTRUCT_4_NODO  = 30;
    public static final int COLUMNA_TIPO_4_ESTRUCT  = 31;
    public static final int COLUMNA_NR_RETEN  = 32;
    public static final int COLUMNA_ANTIGUEDAD  = 33;
    public static final int COLUMNA_PROPIEDAD  = 34;
    public static final int COLUMNA_NRO_ACOMET  = 35;
    public static final int COLUMNA_CON1  = 36;
    public static final int COLUMNA_CAL_FASE_CON1  = 37;
    public static final int COLUMNA_CAL_NEUTRO_CON1  = 38;
    public static final int COLUMNA_CAL_AP_CON1  = 39;
    public static final int COLUMNA_NHIL_CON1  = 40;
    public static final int COLUMNA_CON2  = 41;
    public static final int COLUMNA_CAL_FASE_CON2  = 42;
    public static final int COLUMNA_CAL_NEUTRO_CON2  = 43;
    public static final int COLUMNA_CAL_AP_CON2  = 44;
    public static final int COLUMNA_NHIL_CON2  = 45;
    public static final int COLUMNA_CON3  = 46;
    public static final int COLUMNA_CAL_FASE_CON3  = 47;
    public static final int COLUMNA_CAL_NEUTRO_CON3  = 48;
    public static final int COLUMNA_CAL_AP_CON3  = 49;
    public static final int COLUMNA_NHIL_CON3  = 50;
    public static final int COLUMNA_CON4  = 51;
    public static final int COLUMNA_CAL_FASE_CON4  = 52;
    public static final int COLUMNA_CAL_NEUTRO_CON4  = 53;
    public static final int COLUMNA_CAL_AP_CON4  = 54;
    public static final int COLUMNA_NHIL_CON4  = 55;
    public static final int COLUMNA_FECH_LEVANT_NODO  = 56;
    public static final int COLUMNA_OBSERVACION_NODO  = 57;
    public static final int COLUMNA_NRO_ACOMETIDAS  = 58;
    public static final int COLUMNA_ESPACIO_N2  = 59;
    public static final int COLUMNA_ACOMETIDA_CORRESP  = 60;
    public static final int COLUMNA_NIU = 61;
    public static final int COLUMNA_CONT_ACT = 62;
    public static final int COLUMNA_ID_NODO_ACOMETIDA = 63;
    public static final int COLUMNA_DIRECCION = 64;
    public static final int COLUMNA_CONT_ANTE = 65;
    public static final int COLUMNA_CONT_MARCA = 66;
    public static final int COLUMNA_LATI_USU  = 67;
    public static final int COLUMNA_LONG_USU  = 68;
    public static final int COLUMNA_ALTI_USU  = 69;
    public static final int COLUMNA_TIP_CA = 70;
    public static final int COLUMNA_TIP_AS = 71;
    public static final int COLUMNA_TIP_MBT = 72;
    public static final int COLUMNA_TIP_RST = 73;
    public static final int COLUMNA_CALIBRE = 74;
    public static final int COLUMNA_TABLERO = 75;
    public static final int COLUMNA_FAS_TABLERO = 76;
    public static final int COLUMNA_TIP_SERVICIO = 77;
    public static final int COLUMNA_OBSERVACION_USU = 78;
    public static final int COLUMNA_FECH_LEVANT_USU = 79;
    public static final int COLUMNA_USU_LEVANT_USU = 80;

        /**
     * Determina si la aplicación corre en versiones superiores o iguales
     * a Android LOLLIPOP
     *
     * @return booleano de confirmación
     */
    public static boolean materialDesign() {
        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP;
    }

    /**
     * Copia los datos de una tabla almacenados en un cursor hacia un
     * JSONObject
     *
     * @param c cursor
     * @return objeto jason
     */
    public static JSONObject deCursorAJSONObject( Cursor c) {
        JSONObject jObject = new JSONObject();
        String nomb_trafo;
        String capacidad;
        String zonaur;
        String mpio;
        String propiedad_trafo;
        String tipo;
        String lati_trafo;
        String long_trafo;
        String alt_trafo;
        String tipo_trafo;
        String fech_levant_trafo;
        String observacion_trafo;
        String nro_postes_trafo;
        String espacio_trafo_poste;
        String nro_poste_corresp;
        String nomb_nodo;
        String id_trafo_nodo;
        String lati_nodo;
        String long_nodo;
        String alti_nodo;
        String altura_nodo;
        String material_nodo;
        String estruct_1_nodo;
        String tipo_1_estruct;
        String estruct_2_nodo;
        String tipo_2_estruct;
        String estruct_3_nodo;
        String tipo_3_estruct;
        String estruct_4_nodo;
        String tipo_4_estruct;
        String nr_reten;
        String antiguedad;
        String propiedad_nodo;
        String nro_acomet;
        String con1;
        String cal_fase_con1;
        String cal_neutro_con1;
        String cal_ap_con1;
        String nhil_con1;
        String con2;
        String cal_fase_con2;
        String cal_neutro_con2;
        String cal_ap_con2;
        String nhil_con2;
        String con3;
        String cal_fase_con3;
        String cal_neutro_con3;
        String cal_ap_con3;
        String nhil_con3;
        String con4;
        String cal_fase_con4;
        String cal_neutro_con4;
        String cal_ap_con4;
        String nhil_con4;
        String fech_levant_nodo;
        String observacion_nodo;
        String nro_acometidas;
        String espacio_poste_acometida;
        String nro_acometida_corresp;
        String niu;
        String cont_act;
        String id_nodo_usu;
        String direccion;
        String cont_ante;
        String cont_marca;
        String lati_usu;
        String long_usu;
        String alti_usu;
        String tip_ca;
        String tip_as;
        String tip_mbt;
        String tip_rst;
        String calibre;
        String tablero;
        String fas_tablero;
        String tip_servicio;
        String observacion_usu;
        String fech_levant_usu;
        String usu_levant_usu;

        nomb_trafo = c.getString(COLUMNA_NOMB_TRAFO);
        capacidad = c.getString(COLUMNA_CAPACIDAD);
        zonaur = c.getString(COLUMNA_ZONAUR);
        mpio = c.getString(COLUMNA_MPIO);
        propiedad_trafo = c.getString(COLUMNA_PROPIEDAD_TRAFO);
        tipo = c.getString(COLUMNA_TIPO);
        lati_trafo = c.getString(COLUMNA_LATI_TRAFO);
        long_trafo = c.getString(COLUMNA_LONG_TRAFO);
        alt_trafo = c.getString(COLUMNA_ALT_TRAFO);
        tipo_trafo = c.getString(COLUMNA_TIPO_TRAFO);
        fech_levant_trafo = c.getString(COLUMNA_FECH_LEVANT_TRAFO);
        observacion_trafo = c.getString(COLUMNA_OBSERVACION_TRAFO);
        nro_postes_trafo = c.getString(COLUMNA_NRO_POSTES_TRAFO);
        espacio_trafo_poste = c.getString(COLUMNA_ESPACIO_N1);
        nro_poste_corresp = c.getString(COLUMNA_NRO_POSTE_CORRESP);
        nomb_nodo = c.getString(COLUMNA_NOMB_NODO);
        id_trafo_nodo = c.getString(COLUMNA_ID_TRAFO_NODO);
        lati_nodo = c.getString(COLUMNA_LATI_NODO);
        long_nodo = c.getString(COLUMNA_LONG_NODO);
        alti_nodo = c.getString(COLUMNA_ALTI_NODO);
        altura_nodo = c.getString(COLUMNA_ALTURA_NODO);
        material_nodo = c.getString(COLUMNA_MATERIAL_NODO);
        estruct_1_nodo = c.getString(COLUMNA_ESTRUCT_1_NODO);
        tipo_1_estruct = c.getString(COLUMNA_TIPO_1_ESTRUCT);
        estruct_2_nodo = c.getString(COLUMNA_ESTRUCT_2_NODO);
        tipo_2_estruct = c.getString(COLUMNA_TIPO_2_ESTRUCT);
        estruct_3_nodo = c.getString(COLUMNA_ESTRUCT_3_NODO);
        tipo_3_estruct = c.getString(COLUMNA_TIPO_3_ESTRUCT);
        estruct_4_nodo = c.getString(COLUMNA_ESTRUCT_4_NODO);
        tipo_4_estruct = c.getString(COLUMNA_TIPO_4_ESTRUCT);
        nr_reten = c.getString(COLUMNA_NR_RETEN);
        antiguedad = c.getString(COLUMNA_ANTIGUEDAD);
        propiedad_nodo = c.getString(COLUMNA_PROPIEDAD);
        nro_acomet = c.getString(COLUMNA_NRO_ACOMET);
        con1 = c.getString(COLUMNA_CON1);
        cal_fase_con1 = c.getString(COLUMNA_CAL_FASE_CON1);
        cal_neutro_con1 = c.getString(COLUMNA_CAL_NEUTRO_CON1);
        cal_ap_con1 = c.getString(COLUMNA_CAL_AP_CON1);
        nhil_con1 = c.getString(COLUMNA_NHIL_CON1);
        con2 = c.getString(COLUMNA_CON2);
        cal_fase_con2 = c.getString(COLUMNA_CAL_FASE_CON2);
        cal_neutro_con2 = c.getString(COLUMNA_CAL_NEUTRO_CON2);
        cal_ap_con2 = c.getString(COLUMNA_CAL_AP_CON2);
        nhil_con2 = c.getString(COLUMNA_NHIL_CON2);
        con3 = c.getString(COLUMNA_CON3);
        cal_fase_con3 = c.getString(COLUMNA_CAL_FASE_CON3);
        cal_neutro_con3 = c.getString(COLUMNA_CAL_NEUTRO_CON3);
        cal_ap_con3 = c.getString(COLUMNA_CAL_AP_CON3);
        nhil_con3 = c.getString(COLUMNA_NHIL_CON3);
        con4 = c.getString(COLUMNA_CON4);
        cal_fase_con4 = c.getString(COLUMNA_CAL_FASE_CON4);
        cal_neutro_con4 = c.getString(COLUMNA_CAL_NEUTRO_CON4);
        cal_ap_con4 = c.getString(COLUMNA_CAL_AP_CON4);
        nhil_con4 = c.getString(COLUMNA_NHIL_CON4);
        fech_levant_nodo = c.getString(COLUMNA_FECH_LEVANT_NODO);
        observacion_nodo = c.getString(COLUMNA_OBSERVACION_NODO);
        nro_acometidas = c.getString(COLUMNA_NRO_ACOMETIDAS);
        espacio_poste_acometida = c.getString(COLUMNA_ESPACIO_N2);
        nro_acometida_corresp = c.getString(COLUMNA_ACOMETIDA_CORRESP);
        niu = c.getString(COLUMNA_NIU);
        cont_act = c.getString(COLUMNA_CONT_ACT);
        id_nodo_usu = c.getString(COLUMNA_ID_NODO_ACOMETIDA);
        direccion = c.getString(COLUMNA_DIRECCION);
        cont_ante = c.getString(COLUMNA_CONT_ANTE);
        cont_marca = c.getString(COLUMNA_CONT_MARCA);
        lati_usu = c.getString(COLUMNA_LATI_USU);
        long_usu = c.getString(COLUMNA_LONG_USU);
        alti_usu = c.getString(COLUMNA_ALTI_USU);
        tip_ca = c.getString(COLUMNA_TIP_CA);
        tip_as = c.getString(COLUMNA_TIP_AS);
        tip_mbt = c.getString(COLUMNA_TIP_MBT);
        tip_rst = c.getString(COLUMNA_TIP_RST);
        calibre = c.getString(COLUMNA_CALIBRE);
        tablero = c.getString(COLUMNA_TABLERO);
        fas_tablero = c.getString(COLUMNA_FAS_TABLERO);
        tip_servicio = c.getString(COLUMNA_TIP_SERVICIO);
        observacion_usu = c.getString(COLUMNA_OBSERVACION_USU);
        fech_levant_usu = c.getString(COLUMNA_FECH_LEVANT_USU);
        usu_levant_usu = c.getString(COLUMNA_USU_LEVANT_USU);

        try {
            jObject.put(DatabaseManagerUser.Columnas.NOMB_TRAFO, nomb_trafo);
            jObject.put(DatabaseManagerUser.Columnas.CAPACIDAD, capacidad);
            jObject.put(DatabaseManagerUser.Columnas.ZONAUR, zonaur);
            jObject.put(DatabaseManagerUser.Columnas.MPIO, mpio);
            jObject.put(DatabaseManagerUser.Columnas.PROPIEDAD_TRAFO, propiedad_trafo);
            jObject.put(DatabaseManagerUser.Columnas.TIPO, tipo);
            jObject.put(DatabaseManagerUser.Columnas.LATI_TRAFO, lati_trafo);
            jObject.put(DatabaseManagerUser.Columnas.LONG_TRAFO, long_trafo);
            jObject.put(DatabaseManagerUser.Columnas.ALT_TRAFO, alt_trafo);
            jObject.put(DatabaseManagerUser.Columnas.TIPO_TRAFO, tipo_trafo);
            jObject.put(DatabaseManagerUser.Columnas.FECH_LEVANT_TRAFO, fech_levant_trafo);
            jObject.put(DatabaseManagerUser.Columnas.OBSERVACION_TRAFO, observacion_trafo);
            jObject.put(DatabaseManagerUser.Columnas.NRO_POSTES_TRAFO, nro_postes_trafo);
            jObject.put(DatabaseManagerUser.Columnas.ESPACIO_N1, espacio_trafo_poste);
            jObject.put(DatabaseManagerUser.Columnas.NRO_POSTE_CORRESP, nro_poste_corresp);
            jObject.put(DatabaseManagerUser.Columnas.NOMB_NODO, nomb_nodo);
            jObject.put(DatabaseManagerUser.Columnas.ID_TRAFO_NODO, id_trafo_nodo);
            jObject.put(DatabaseManagerUser.Columnas.LATI_NODO, lati_nodo);
            jObject.put(DatabaseManagerUser.Columnas.LONG_NODO, long_nodo);
            jObject.put(DatabaseManagerUser.Columnas.ALTI_NODO, alti_nodo);
            jObject.put(DatabaseManagerUser.Columnas.ALTURA_NODO, altura_nodo);
            jObject.put(DatabaseManagerUser.Columnas.MATERIAL_NODO, material_nodo);
            jObject.put(DatabaseManagerUser.Columnas.ESTRUCT_1_NODO, estruct_1_nodo);
            jObject.put(DatabaseManagerUser.Columnas.TIPO_1_ESTRUCT, tipo_1_estruct);
            jObject.put(DatabaseManagerUser.Columnas.ESTRUCT_2_NODO, estruct_2_nodo);
            jObject.put(DatabaseManagerUser.Columnas.TIPO_2_ESTRUCT, tipo_2_estruct);
            jObject.put(DatabaseManagerUser.Columnas.ESTRUCT_3_NODO, estruct_3_nodo);
            jObject.put(DatabaseManagerUser.Columnas.TIPO_3_ESTRUCT, tipo_3_estruct);
            jObject.put(DatabaseManagerUser.Columnas.ESTRUCT_4_NODO, estruct_4_nodo);
            jObject.put(DatabaseManagerUser.Columnas.TIPO_4_ESTRUCT, tipo_4_estruct);
            jObject.put(DatabaseManagerUser.Columnas.NR_RETEN, nr_reten);
            jObject.put(DatabaseManagerUser.Columnas.ANTIGUEDAD, antiguedad);
            jObject.put(DatabaseManagerUser.Columnas.PROPIEDAD, propiedad_nodo);
            jObject.put(DatabaseManagerUser.Columnas.NRO_ACOMET, nro_acomet);
            jObject.put(DatabaseManagerUser.Columnas.CON1, con1);
            jObject.put(DatabaseManagerUser.Columnas.CAL_FASE_CON1, cal_fase_con1);
            jObject.put(DatabaseManagerUser.Columnas.CAL_NEUTRO_CON1, cal_neutro_con1);
            jObject.put(DatabaseManagerUser.Columnas.CAL_AP_CON1, cal_ap_con1);
            jObject.put(DatabaseManagerUser.Columnas.NHIL_CON1, nhil_con1);
            jObject.put(DatabaseManagerUser.Columnas.CON2, con2);
            jObject.put(DatabaseManagerUser.Columnas.CAL_FASE_CON2, cal_fase_con2);
            jObject.put(DatabaseManagerUser.Columnas.CAL_NEUTRO_CON2, cal_neutro_con2);
            jObject.put(DatabaseManagerUser.Columnas.CAL_AP_CON2, cal_ap_con2);
            jObject.put(DatabaseManagerUser.Columnas.NHIL_CON2, nhil_con2);
            jObject.put(DatabaseManagerUser.Columnas.CON3, con3);
            jObject.put(DatabaseManagerUser.Columnas.CAL_FASE_CON3, cal_fase_con3);
            jObject.put(DatabaseManagerUser.Columnas.CAL_NEUTRO_CON3, cal_neutro_con3);
            jObject.put(DatabaseManagerUser.Columnas.CAL_AP_CON3, cal_ap_con3);
            jObject.put(DatabaseManagerUser.Columnas.NHIL_CON3, nhil_con3);
            jObject.put(DatabaseManagerUser.Columnas.CON4, con4);
            jObject.put(DatabaseManagerUser.Columnas.CAL_FASE_CON4, cal_fase_con4);
            jObject.put(DatabaseManagerUser.Columnas.CAL_NEUTRO_CON4, cal_neutro_con4);
            jObject.put(DatabaseManagerUser.Columnas.CAL_AP_CON4, cal_ap_con4);
            jObject.put(DatabaseManagerUser.Columnas.NHIL_CON4, nhil_con4);
            jObject.put(DatabaseManagerUser.Columnas.FECH_LEVANT_NODO, fech_levant_nodo);
            jObject.put(DatabaseManagerUser.Columnas.OBSERVACION_NODO, observacion_nodo);
            jObject.put(DatabaseManagerUser.Columnas.NRO_ACOMETIDAS, nro_acometidas);
            jObject.put(DatabaseManagerUser.Columnas.ESPACIO_N2, espacio_poste_acometida);
            jObject.put(DatabaseManagerUser.Columnas.ACOMETIDA_CORRESP, nro_acometida_corresp);
            jObject.put(DatabaseManagerUser.Columnas.NIU, niu);
            jObject.put(DatabaseManagerUser.Columnas.CONT_ACT,cont_act );
            jObject.put(DatabaseManagerUser.Columnas.ID_NODO_ACOMETIDA,id_nodo_usu );
            jObject.put(DatabaseManagerUser.Columnas.DIRECCION,direccion );
            jObject.put(DatabaseManagerUser.Columnas.CONT_ANTE, cont_ante );
            jObject.put(DatabaseManagerUser.Columnas.CONT_MARCA, cont_marca);
            jObject.put(DatabaseManagerUser.Columnas.LATI_USU, lati_usu);
            jObject.put(DatabaseManagerUser.Columnas.LONG_USU, long_usu);
            jObject.put(DatabaseManagerUser.Columnas.ALTI_USU, alti_usu);
            jObject.put(DatabaseManagerUser.Columnas.TIP_CA, tip_ca);
            jObject.put(DatabaseManagerUser.Columnas.TIP_AS, tip_as);
            jObject.put(DatabaseManagerUser.Columnas.TIP_MBT, tip_mbt);
            jObject.put(DatabaseManagerUser.Columnas.TIP_RST, tip_rst);
            jObject.put(DatabaseManagerUser.Columnas.CALIBRE, calibre);
            jObject.put(DatabaseManagerUser.Columnas.TABLERO, tablero);
            jObject.put(DatabaseManagerUser.Columnas.FAS_TABLERO, fas_tablero);
            jObject.put(DatabaseManagerUser.Columnas.TIP_SERVICIO, tip_servicio);
            jObject.put(DatabaseManagerUser.Columnas.OBSERVACION_USU, observacion_usu);
            jObject.put(DatabaseManagerUser.Columnas.FECH_LEVANT_USU, fech_levant_usu);
            jObject.put(DatabaseManagerUser.Columnas.USU_LEVANT_USU, usu_levant_usu);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        Log.i("Cursor a JSONObject", String.valueOf(jObject));

        return jObject;
    }
}
